Feat/finished home
aisl1n/ZZFRONT pull request #5
Opened 2024-10-09 12:26 UTC by aisl1n

- Created bannerCarousel
- Created bannerCollections
- Created bannerPromotion
- Adjusted footer and navbar components
- Created recommendedSection
- Created types folder and product type
- Created utils folder and returnFirstFiveProducts method
- Added db.json to source code

2024-10-09 14:06 UTC, sergioandrade requested changes

2024-10-09 14:06 UTC, sergioandrade commented on src/components/bannerCarousel/index.tsx
> +    <>
Como tu ta usando apenas um elemento html para englobar o componente, não tem a necessidade de usar o fragment 😉

2024-10-09 14:06 UTC, sergioandrade commented on src/components/bannerCollections/constants.ts
> +export const COLLECTION_BUTTON_LABEL = "ver coleção";
Será que não faria sentido ser tudo um objeto com cada texto sendo uma propriedade? Pois se tratam do mesmo contexto, o conteudo do bannerCollections

2024-10-09 14:06 UTC, sergioandrade commented on src/components/bannerPromotion/constants.ts
> +  "em R$ 9,90 para regiões sul, sudeste e capitais de ne e co.";
To questionando mesmo, não to dizendo pra mudar. Mas novamente, será que não vale a pena usar isso em um objeto?

2024-10-09 14:06 UTC, sergioandrade commented on src/components/recommendedSection/constants.ts
> +export const RECOMMENDED_SECTION_SEE_ALL = "ver todos os produtos";
Aqui vale o mesmo questionamento anterior.

2024-10-09 14:06 UTC, sergioandrade commented on src/utils/index.ts
> +  return data.slice(0, 5);
Aqui o nome da função está com um contexto muito bom, me dizendo que vai retornar somente os 5 produtos.

Apesar disso, considerando um cenário hiptotético, tu está usando essa function em varios lugares da tua aplicação, afinal, ela se trata de um útil. 

Se por acaso, um dia precisarmos mudar pra 6 produtos, teremos que mudar o nome da função em todos os lugares onde ela é utilizada, e isso vai impactar em testarmos a aplicação novamente em todos os lugares onde ela foi chamada.

Pra solucionar isso, podemos ir por uma abordagem de criar um nome genérico pra função, por exemplo `returnListOfProducts` onde tu poderia, ou passar um parâmetro pra dizer que são 5, ou deixar o 5 em uma const em uppercase, pois se trata de um valor hard coded (Isso evita os Magic Numbers).

Como escolher entre uma ou outra?

Se existe a possibilidade de tu usar esse útil com mais de 5 itens, vai pelo caminho de passar o parâmetro.
Se sempre vai ser os 5, ai tu pode criar a const com o valor chumbado.

2024-10-09 16:54 UTC, aisl1n commented on src/components/bannerCarousel/index.tsx
> +    <>
De fato!

2024-10-09 16:54 UTC, aisl1n commented on src/components/bannerCollections/constants.ts
> +export const COLLECTION_BUTTON_LABEL = "ver coleção";
Faz sentido sim!

2024-10-09 20:27 UTC, sergioandrade requested changes

2024-10-09 20:27 UTC, sergioandrade commented on src/components/recommendedSection/constants.ts
> +export const MAX_FIVE_PRODUCTS = 5;
Talvez se usarmos um nome mais genérico, ao trocar o valor da const, alteramos apenas o valor e não o seu nome:

Algo assim:
```jsx
export const MAX_PRODUCTS_TO_SHOW = 5;
```

2024-10-09 20:27 UTC, sergioandrade commented on src/components/recommendedSection/index.tsx
> +  const firstFive = returnListOfProducts(data, MAX_FIVE_PRODUCTS);
Aqui também eu não atrelaria uma const para five, pois se por ventura mude essa quantidade, a variável não ta com um nome condizente.

2024-10-09 23:09 UTC, aisl1n commented on src/components/recommendedSection/constants.ts
> +export const MAX_FIVE_PRODUCTS = 5;
saquei!

2024-10-10 12:24 UTC, sergioandrade approved these changes

2024-10-10 12:25 UTC, merged